name: py36-env
channels: 
  - conda-forge
  - ioam
  - soumith
dependencies:
  - python=3.6
  - numpy
  - pandas
  - pytorch
  - torchvision
  - seaborn
  - matplotlib
  - jupyter
  - psycopg2
  - pillow
  - geopy
  - pygrib
  - sklearn
  - mlxtend